apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-cicd-k8s.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "devops-cicd-k8s.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
