  apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-cicd-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-cicd-k8s
  template:
    metadata:
      labels:
        app: devops-cicd-k8s
    spec:
      containers:
      - name: app
        image: YOUR_IMAGE
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
